# Generated by Django 3.1.7 on 2021-03-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idTipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lugarResidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ciudad'),
        ),
    ]
